services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/abdullah/Desktop/PONTISBE
      - /home/abdullah/Desktop/PONTISBE/PONTISBE/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production